### ISSUE TITLE
Help wanted: Finding a new owner.

### ISSUE THREAD

**Issue by nearbydelta** [winnekes/itypescript#23]
Thank you all for using ITypescript even though I didn't manage it well.
First of all, I'm very sorry for the delay in the update.

I write this issue because I think it is better to transfer ownership to someone else who can update this repository.

When I first uploaded this repository, I didn't know that this many people would use ITypescript. So I believed I could manage it by myself in my leisure time.

But things have changed. I don't use Typescript anymore, so I became paying less attention to ITypescript than before. To make ITypescript better, hence, **I concluded that this repository needs someone else to fix listed issues.**

Currently, I'm considering **'ownership transfer.'** ITypescript should be managed by better people who can pay more attention to it than me. **If anyone is interested in developing and updating this repository, please leave a reply.** Then, I can transfer the ownership of the repository to the person or organization who replied.

**Or, if you have any better options, please leave a comment here.**

Once again, thank you for using ITypescript, and sorry for the unhandled issues.

**Comment by winnekes** [comment]
I am willing to take over ownership and maintain this repository, let me know about your decision

**Comment by winnekes** [comment]
@nearbydelta i haven't heard back from you - is this still an option?

**Comment by nearbydelta** [comment]
@winnekes Oh, sorry for the late reply. Yes, this is still an option. I'll transfer the ownership of this repository to you. Thanks.

**Comment by winnekes** [comment]
awesome! i appreciate this, hope i can continue what you started!
